const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'),cfg=require('../qa/first-run/browser-config.json'),OUT=path.resolve(process.env.QA_OUTPUT||'qa-artifacts/first-run'),BASE=process.env.BASE_ROOT;assert(BASE,'Immutable BASE_ROOT required');fs.mkdirSync(OUT,{recursive:true});const servers=[];const report={baseCommit:require('../qa/first-run/baseline.json').baseCommit,headCommit:process.env.SOURCE_SHA||'local-candidate',indexSHA256:crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,'index.html'))).digest('hex'),repo:cfg.repo,checks:[],geometry:[],cases:{},screenshots:[],limitations:['Chromium emulation, not physical devices or WebKit/Firefox','No user study or usability score','View changes do not claim game-data verification']};
async function serve(root){const s=http.createServer((q,r)=>{const u=new URL(q.url,'http://local'),prefix='/'+cfg.repo+'/';if(!u.pathname.startsWith(prefix)){r.writeHead(404);r.end();return}const f=path.resolve(root,decodeURIComponent(u.pathname.slice(prefix.length))||'index.html');if(!f.startsWith(root)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){r.writeHead(404);r.end();return}const ext=path.extname(f);r.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'})[ext]||'application/octet-stream');fs.createReadStream(f).pipe(r)});await new Promise(ok=>s.listen(0,'127.0.0.1',ok));servers.push(s);return`http://127.0.0.1:${s.address().port}/${cfg.repo}/`}
async function settle(p){await p.locator(cfg.ready).first().waitFor();if(cfg.repo==='ro-best-status')await p.waitForFunction(()=>document.querySelector('#results-panel').getAttribute('aria-busy')==='false');else await p.waitForTimeout(250);await p.evaluate(()=>document.fonts.ready);}
async function reveal(p,selector){const ancestors=await p.locator(selector).evaluate(e=>{const a=[];while(e){if(e.tagName==='DETAILS'&&!e.open)a.push(e);e=e.parentElement;}return a.reverse().map(x=>x.id||null)});if(ancestors.length)await p.locator(selector).evaluate(e=>{while(e){if(e.tagName==='DETAILS')e.open=true;e=e.parentElement;}});}
async function edit(p,fields){for(const[id,v]of Object.entries(fields)){await reveal(p,'#'+id);const el=p.locator('#'+id),type=await el.evaluate(x=>x.tagName);if(type==='SELECT')await el.selectOption(String(v));else await el.fill(String(v));await el.press('Tab');}await settle(p);}
async function snapshot(p){return p.evaluate(repo=>{const t=id=>document.getElementById(id)?.textContent.replace(/\s+/g,' ').trim();if(repo==='ro-leveling-map')return{summary:t('summary'),rows:[...document.querySelectorAll('#mapTable tbody tr')].slice(0,5).map(e=>e.textContent.replace(/\s+/g,' ').trim())};if(repo==='ro-reform-preparation')return Object.fromEntries(['total','material-cost','npc-cost','shopping-list','recipe-steps','target-name'].map(id=>[id,t(id)]));if(repo==='dim_glacier_planner')return Object.fromEntries(['cost_base','cost_enchant','cost_refine','total_zeny','total_thb','shop_list','list_steps'].map(id=>[id,t(id)]));return[...document.querySelectorAll('.result-card')].map(e=>({activity:e.dataset.activity,state:e.dataset.state,rate:e.querySelector('.big-rate')?.textContent,stats:e.querySelector('.allocation-grid')?.textContent,points:e.querySelector('.card-points')?.textContent,caution:e.querySelector('.raw-label')?.textContent}));},cfg.repo);}
async function stored(p){return p.evaluate(()=>({url:location.href,local:{...localStorage}}));}
(async()=>{const browser=await chromium.launch();try{for(const[kind,root]of[['before',BASE],['after',ROOT]]){const url=await serve(root);for(const width of[360,390,768,1440])for(const colorScheme of cfg.themes){const ctx=await browser.newContext({viewport:{width,height:900},colorScheme,reducedMotion:'reduce',serviceWorkers:'block'}),p=await ctx.newPage();await p.goto(url,{waitUntil:'networkidle'});await settle(p);const g=await p.evaluate(c=>{const r=s=>{const e=document.querySelector(s);if(!e)return null;const b=e.getBoundingClientRect();return{y:b.y,height:b.height,width:b.width}};return{firstInput:r(c.first),result:r(c.result),cue:r(c.cue),overflow:document.documentElement.scrollWidth-innerWidth,visibleInputs:[...document.querySelectorAll('input,select')].filter(e=>e.checkVisibility()&&!e.closest('details:not([open])')).length,openDetails:[...document.querySelectorAll('details[open]')].filter(e=>e.checkVisibility()&&!e.parentElement.closest('details:not([open])')).length};},cfg);report.geometry.push({kind,width,colorScheme,...g});const shot=`${kind}-${width}-${colorScheme}.png`;await p.screenshot({path:path.join(OUT,shot)});report.screenshots.push(shot);
if(kind==='after'){const bg=report.geometry.find(x=>x.kind==='before'&&x.width===width&&x.colorScheme===colorScheme);assert(g.overflow<=bg.overflow+1,'no new horizontal overflow');assert(g.cue&&g.cue.y<900,'first-run cue visible in first viewport');const ids=await p.locator('[id]').evaluateAll(es=>es.map(e=>e.id));assert.equal(new Set(ids).size,ids.length,'no duplicate IDs');const dangling=await p.locator('label[for]').evaluateAll(es=>es.filter(e=>!e.control).map(e=>e.htmlFor));assert.deepEqual(dangling,[],'labels still target real controls');const before=await snapshot(p),state=await stored(p);
if(cfg.repo==='ro-best-status'){for(const a of['rune','poison','potion','all']){const radio=p.locator(`[name="first-activity"][value="${a}"]`);await radio.focus();await p.keyboard.press('Space');assert.equal(await p.locator('.result-card:visible').count(),a==='all'?3:1);assert.equal(await p.locator('.profile-control:visible').count(),a==='all'?3:1);assert.deepEqual(await snapshot(p),before,'view selection does not change any result');assert.deepEqual(await stored(p),state,'view selection does not change URL or saved settings');}assert(await p.locator('.notice').isVisible());assert((await p.locator('.notice').innerText()).includes('ข้อโต้แย้ง'));assert((await p.locator('.notice').innerText()).includes('ไม่ใช่อัตราสำเร็จที่ยืนยันจากเซิร์ฟเวอร์'));await p.locator('[name="first-activity"][value="rune"]').check();}
if(cfg.repo==='dim_glacier_planner'){assert.equal(await p.locator('#market-price-details').getAttribute('open'),null);const summary=p.locator('#market-price-details > summary');await summary.focus();await p.keyboard.press('Space');assert(await p.locator('#rate_thb').isVisible());await p.keyboard.press('Space');assert.equal(await p.locator('#market-price-details').getAttribute('open'),null);assert.deepEqual(await snapshot(p),before);assert.deepEqual(await stored(p),state);assert(await p.locator('#default_price_date').isVisible());assert(await p.locator('#price_last_modified').isVisible());assert(await p.locator('.market-warning').isVisible());if(width<=768)assert(g.firstInput.y<bg.firstInput.y,'primary planner reached before market panel');if(width<=768)assert(g.result.y<bg.result.y,'total reached earlier on mobile without covering planner controls');}
if(cfg.repo==='ro-leveling-map'){assert.equal(await p.locator('#advancedSettings').getAttribute('open'),null);assert(await p.locator('#eventInfo').isVisible());assert(!(await p.locator('#eventInfo').evaluate(e=>!!e.closest('details'))));const summary=p.locator('#advancedSettings > summary');await summary.focus();await p.keyboard.press('Space');await p.keyboard.press('Space');assert.deepEqual(await snapshot(p),before);assert.deepEqual(await stored(p),state);if(await p.locator('.jump-results').isVisible()){await p.locator('.jump-results').click();await p.waitForURL('**/#results');}}
if(cfg.repo==='ro-reform-preparation'){await p.locator('.first-run-start').focus();await p.keyboard.press('Enter');await p.waitForURL('**/#main');await p.locator('.first-run-result').focus();await p.keyboard.press('Enter');await p.waitForURL('**/#results');assert.deepEqual(await snapshot(p),before);assert(await p.locator('#example-banner').isVisible());}
report.checks.push({width,colorScheme,status:'PASS',checks:'first cue, original or lower overflow, unique IDs, native labels, minimum path, view-only state/output invariants'});}
await ctx.close();}
const ctx=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'}),p=await ctx.newPage();await p.goto(url,{waitUntil:'networkidle'});await settle(p);report.cases[kind]=[];for(const fixture of cfg.cases){await edit(p,fixture.fields);const value=await snapshot(p);report.cases[kind].push({name:fixture.name,input:fixture.fields,output:value});if(kind==='after')assert.deepEqual(value,report.cases.before.find(x=>x.name===fixture.name).output,fixture.name+' exact original output');}await ctx.close();}
report.status='PASS';}catch(e){report.status='FAIL';report.error=e.stack;process.exitCode=1;}finally{await browser.close();for(const s of servers)await new Promise(ok=>s.close(ok));fs.writeFileSync(path.join(OUT,'first-run-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}})();
